import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import {
  AppBar,
  Box,
  Button,
  Drawer,
  IconButton,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Toolbar,
  Typography,
} from '@mui/material'
import { Menu as MenuIcon, MoveToInbox as InboxIcon } from '@mui/icons-material'
import { APP_NAME, PAGE_NAME } from '@/config'

export default function Layout({ children }: any) {
  const router = useRouter()
  const { t } = useTranslation('common')

  const [open, setOpen] = useState(false)

  const toggleDrawer = () => {
    setOpen(!open)
  }

  const goto = (path: string) => {
    router.push(path)
    setOpen(!open)
  }

  const changeTo = router.locale === 'en' ? 'ja' : 'en'

  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="static">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
            onClick={toggleDrawer}
          >
            <MenuIcon />
          </IconButton>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            {APP_NAME}
          </Typography>
          <Link href={router.route} locale={changeTo}>
            <Button variant="outlined" sx={{ color: 'white' }}>
              {t('change-locale', { changeTo })}
            </Button>
          </Link>
        </Toolbar>
      </AppBar>
      <Drawer open={open} onClose={toggleDrawer}>
        <Box sx={{ width: 250 }}>
          <List>
            <ListItem disablePadding>
              <ListItemButton onClick={() => goto('/collections')}>
                <ListItemIcon>
                  <InboxIcon />
                </ListItemIcon>
                <ListItemText>{PAGE_NAME.COLLECTIONS.INDEX}</ListItemText>
              </ListItemButton>
            </ListItem>
          </List>
        </Box>
      </Drawer>
      <main>{children}</main>
    </>
  )
}
